# frozen_string_literal: true

require_relative "test_helper"

class EnvrcWriterTest < Minitest::Test
  include TestHelpers

  # env_key mapping

  def test_env_key_postgres_maps_to_db_port
    assert_equal "DB_PORT", Portkey::EnvrcWriter.env_key("postgres")
  end

  def test_env_key_postgresql_maps_to_db_port
    assert_equal "DB_PORT", Portkey::EnvrcWriter.env_key("postgresql")
  end

  def test_env_key_app_maps_to_app_port
    assert_equal "APP_PORT", Portkey::EnvrcWriter.env_key("app")
  end

  def test_env_key_redis_maps_to_redis_port
    assert_equal "REDIS_PORT", Portkey::EnvrcWriter.env_key("redis")
  end

  def test_env_key_custom_service
    assert_equal "MEMCACHED_PORT", Portkey::EnvrcWriter.env_key("memcached")
    assert_equal "OTHER_PORT", Portkey::EnvrcWriter.env_key("other")
  end

  # generate_envrc

  def test_generate_envrc_produces_export_lines
    data = { "path" => "/tmp/myapp", "app" => 3000, "postgres" => 5432, "redis" => 6379 }
    content = Portkey::EnvrcWriter.generate_envrc("myapp", data)

    assert_includes content, "export APP_PORT=3000"
    assert_includes content, "export DB_PORT=5432"
    assert_includes content, "export REDIS_PORT=6379"
    assert_includes content, "# Generated by portkey"
    assert_includes content, "# Project: myapp"
  end

  def test_generate_envrc_skips_path_key
    data = { "path" => "/tmp/myapp", "app" => 3000 }
    content = Portkey::EnvrcWriter.generate_envrc("myapp", data)

    refute_includes content, "/tmp/myapp"
    refute_includes content, "export PATH"
  end

  def test_generate_envrc_includes_custom_services
    data = { "path" => "/tmp", "app" => 3000, "other" => 1234 }
    content = Portkey::EnvrcWriter.generate_envrc("myapp", data)

    assert_includes content, "export APP_PORT=3000"
    assert_includes content, "export OTHER_PORT=1234"
  end

  # generate_dotenv

  def test_generate_dotenv_produces_plain_lines
    data = { "path" => "/tmp/myapp", "app" => 3000, "postgres" => 5432 }
    content = Portkey::EnvrcWriter.generate_dotenv("myapp", data)

    assert_includes content, "APP_PORT=3000"
    assert_includes content, "DB_PORT=5432"
    refute_includes content, "export "
  end

  # key deduplication

  def test_generate_envrc_deduplicates_keys
    # postgres and pg both map to DB_PORT — only the first should appear
    data = { "path" => "/tmp", "postgres" => 5432, "pg" => 9999 }
    content = Portkey::EnvrcWriter.generate_envrc("myapp", data)

    assert_includes content, "export DB_PORT=5432"
    refute_includes content, "9999"
    assert_equal 1, content.scan("DB_PORT").count
  end

  def test_generate_dotenv_deduplicates_keys
    data = { "path" => "/tmp", "postgres" => 5432, "pg" => 9999 }
    content = Portkey::EnvrcWriter.generate_dotenv("myapp", data)

    assert_includes content, "DB_PORT=5432"
    refute_includes content, "9999"
    assert_equal 1, content.scan("DB_PORT").count
  end

  # write with modes

  def test_write_envrc_mode_creates_envrc_file
    with_temp_project_dir do |dir|
      data = { "path" => dir, "app" => 3000, "postgres" => 5432 }
      written = Portkey::EnvrcWriter.write("testapp", data, mode: "envrc")

      assert_equal [File.join(dir, ".envrc")], written
      assert File.exist?(File.join(dir, ".envrc"))
      refute File.exist?(File.join(dir, ".env"))

      content = File.read(File.join(dir, ".envrc"))
      assert_includes content, "export APP_PORT=3000"
    end
  end

  def test_write_dotenv_mode_creates_env_file
    with_temp_project_dir do |dir|
      data = { "path" => dir, "app" => 3000, "postgres" => 5432 }
      written = Portkey::EnvrcWriter.write("testapp", data, mode: "dotenv")

      assert_equal [File.join(dir, ".env")], written
      assert File.exist?(File.join(dir, ".env"))
      refute File.exist?(File.join(dir, ".envrc"))

      content = File.read(File.join(dir, ".env"))
      assert_includes content, "APP_PORT=3000"
      refute_includes content, "export "
    end
  end

  def test_write_both_mode_creates_both_files
    with_temp_project_dir do |dir|
      data = { "path" => dir, "app" => 3000 }
      written = Portkey::EnvrcWriter.write("testapp", data, mode: "both")

      assert_equal 2, written.size
      assert File.exist?(File.join(dir, ".envrc"))
      assert File.exist?(File.join(dir, ".env"))

      envrc = File.read(File.join(dir, ".envrc"))
      dotenv = File.read(File.join(dir, ".env"))
      assert_includes envrc, "export APP_PORT=3000"
      assert_includes dotenv, "APP_PORT=3000"
      refute_includes dotenv, "export "
    end
  end

  def test_write_overwrites_existing_files
    with_temp_project_dir do |dir|
      File.write(File.join(dir, ".envrc"), "old content")

      data = { "path" => dir, "app" => 3000 }
      Portkey::EnvrcWriter.write("testapp", data, mode: "envrc")

      content = File.read(File.join(dir, ".envrc"))
      refute_includes content, "old content"
      assert_includes content, "export APP_PORT=3000"
    end
  end

  def test_write_raises_if_no_path
    assert_raises(Portkey::Error) do
      Portkey::EnvrcWriter.write("testapp", { "app" => 3000 })
    end
  end

  def test_write_raises_if_directory_missing
    assert_raises(Portkey::Error) do
      Portkey::EnvrcWriter.write("testapp", { "path" => "/nonexistent/path", "app" => 3000 })
    end
  end

  def test_direnv_allow_failure_does_not_crash
    with_temp_project_dir do |dir|
      data = { "path" => dir, "app" => 3000 }
      written = Portkey::EnvrcWriter.write("testapp", data, mode: "envrc")
      assert File.exist?(written.first)
    end
  end
end
