# frozen_string_literal: true

require "open3"

module Portkey
  module EnvrcWriter
    SERVICE_KEY_MAP = {
      "postgres" => "DB_PORT",
      "postgresql" => "DB_PORT",
      "pg" => "DB_PORT"
    }.freeze

    module_function

    def env_key(service_name)
      SERVICE_KEY_MAP.fetch(service_name, "#{service_name.upcase}_PORT")
    end

    def generate_envrc(project_name, project_data)
      lines = ["# Generated by portkey — do not edit manually"]
      lines << "# Project: #{project_name}"
      lines << ""

      seen = {}
      project_data.each do |key, value|
        next if key == "path"
        next unless value.is_a?(Integer)

        k = env_key(key)
        next if seen.key?(k)
        seen[k] = true

        lines << "export #{k}=#{value}"
      end

      lines.join("\n") + "\n"
    end

    def generate_dotenv(project_name, project_data)
      lines = ["# Generated by portkey — do not edit manually"]
      lines << "# Project: #{project_name}"
      lines << ""

      seen = {}
      project_data.each do |key, value|
        next if key == "path"
        next unless value.is_a?(Integer)

        k = env_key(key)
        next if seen.key?(k)
        seen[k] = true

        lines << "#{k}=#{value}"
      end

      lines.join("\n") + "\n"
    end

    def write(project_name, project_data, mode: "envrc")
      path = project_data["path"]
      raise Portkey::Error, "No path defined for project '#{project_name}'" unless path

      expanded = File.expand_path(path)
      unless Dir.exist?(expanded)
        raise Portkey::Error, "Project directory does not exist: #{expanded}"
      end

      written = []

      if mode == "envrc" || mode == "both"
        envrc_path = File.join(expanded, ".envrc")
        File.write(envrc_path, generate_envrc(project_name, project_data))
        direnv_allow(expanded)
        written << envrc_path
      end

      if mode == "dotenv" || mode == "both"
        dotenv_path = File.join(expanded, ".env")
        File.write(dotenv_path, generate_dotenv(project_name, project_data))
        written << dotenv_path
      end

      written
    end

    def direnv_allow(dir)
      Open3.capture2("direnv", "allow", chdir: dir)
    rescue Errno::ENOENT
      warn "Warning: direnv not found. Run `direnv allow` manually in #{dir}"
    end
  end
end
